import mongoose from "mongoose";

//This is depricated bassically, I could never get the databaase stuff working for the supplies page
const suppliesSchema = new mongoose.Schema({
  supplieID: { type: Array },
  email: { type: String, required: true, unique: true },
  suppliesTable: [
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
    { type: Array },
  ],
});

const Supplies =
  mongoose.models.User || mongoose.model("Supplies", suppliesSchema);
export default Supplies;
