"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("@/styles/globals.css");
const sidebar_1 = require("@/components/ui/sidebar");
const app_sidebar_1 = require("@/components/app-sidebar");
const inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<html>
      <body>
      <sidebar_1.SidebarProvider>
        <app_sidebar_1.AppSidebar />
        <sidebar_1.SidebarTrigger className="-ml-1"/>
          <sidebar_1.SidebarInset>
            {children}
          </sidebar_1.SidebarInset>
      </sidebar_1.SidebarProvider>
      </body>
    </html>);
}
